-- Require modules
require "src/config"
require "src/browser"
require "src/spectacle"
require "src/bluetooth"
require "src/idasen"
require "src/travel"
-- require "src/caffeinate"
require "src/apps"
require "src/screens"
